sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull jumperio/vlab-gcc-arm:latest

script:
- docker run -v $PWD:/my_files_in_docker --entrypoint /usr/bin/make jumperio/vlab-gcc-arm -C /my_files_in_docker/examples/ble_peripheral/ble_app_blinky/pca10040/s132/armgcc